language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
install: "pip install -r src/datascope/requirements/production.txt"
# command to run tests
script: cd src && python manage.py test --settings=datascope.settings_test
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
  - DJANGO_CONTEXT=host
