SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

GOOGLE_API_KEY = ''
INDICO_API_KEY = ''
FACEPLUSPLUS_PUBLIC_KEY = ''
FACEPLUSPLUS_PRIVATE_KEY = ''
RAVEN_DSN = ''

EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

LOCAFORA_PASSWORD = ''

WIKI_USER = ''
WIKI_PASSWORD = ''
