from datascope.secrets import FACEPLUSPLUS_PUBLIC_KEY, FACEPLUSPLUS_PRIVATE_KEY

API_KEY = FACEPLUSPLUS_PUBLIC_KEY
API_SECRET = FACEPLUSPLUS_PRIVATE_KEY
FACE_SET_NAME = 'Installation48db'
FACE_SET_TRY_CREATE = True
